services:
  rei:
    container_name: rei
    image: rei:latest
    hostname: "machina-mori"
    restart: always

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 13389:3389

    devices:
      - /dev/net/tun

    volumes:
      # Persist workspace and tools data
      - ./resources/bin:/opt/bin:z
      - ./resources/lists:/opt/lists:z
      - ./resources/tools:/opt/tools:z
      - ./resources/linux:/opt/resources/linux:z

      - ./workspace:/workspace:z
      # DMS colors
      - /home/oxce5/.cache/DankMaterialShell/dms-colors.json:/home/kali/.cache/DankMaterialShell/dms-colors.json:z,ro
      - /home/oxce5/.config/DankMaterialShell/settings.json:/home/kali/.config/DankMaterialShell/settings.json:z,ro

      # Persist C2 data
      - ./home/sliver/server:/root/.sliver:z
      - ./home/sliver/client:/home/kali/.sliver-client:z
      # Save bash history
      - ./home/bash_history:/home/kali/.bash_history:z

    networks:
      - ctflab
      # - qemunet

    sysctls:
      - net.ipv4.conf.all.forwarding=1

networks:
  ctflab:
    external: true
    # driver: bridge
  # qemunet:
  #   driver: macvlan
  #   driver_opts:
  #     parent: virbr0
  #   ipam:
  #     config:
  #       - subnet: 192.168.122.0/24
  #         gateway: 192.168.122.1
